forum/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
  	resources :comments
  end

  root  'posts#index'
  match 'about', controller: 'posts', action: 'about', via: 'get'
  match 'about' => 'posts#about', via: 'get'
  match 'contact', controller: 'posts', action: 'contact', via: 'get'
  match 'contact' => 'posts#contact', via: 'get'
end

forum/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

forum/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

forum/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

forum/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:comment))
		@comment.user_id = current_user.id if current_user
		@comment.save 

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end

	def edit
		if current_user.id == Post.find(params[:post_id]).user.id
			@post = Post.find(params[:post_id])
			@comment = @post.comments.find(params[:id])
		else
			redirect_to :back
		end
	end

	def update
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to post_path(@post)
		else
			render 'edit'
		end
	end

	def destroy
		if current_user.id == Post.find(params[:post_id]).user.id
			@post = Post.find(params[:post_id])
			@comment = @post.comments.find(params[:id])
			@comment.destroy
			redirect_to post_path(@post)
		else
			redirect_to :back
		end 
	end
end

forum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:about, :contact]

	def index
		@posts = Post.all.order("created_at DESC")
	end

	def about
	end

	def contact
	end

	def show
	end


	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if current_user.id == Post.find(params[:id]).user.id
			if @post.update(post_params)
				redirect_to @post
			else
				render 'edit'
			end
		else
			redirect_to @post
		end
	end

	def destroy
		if current_user.id == Post.find(params[:id]).user.id
			@post.destroy
			redirect_to root_path
		else
			redirect_to :back
		end
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/comments_helper.rb
module CommentsHelper
end

forum/app/helpers/posts_helper.rb
module PostsHelper
end

forum/app/views/comments/_comment.html.haml
.card-panel.z-depth-2
	%h5= comment.comment
	%p
		Publicado por 
		= comment.user.username
		| email: 
		= comment.user.email

	- if current_user == Comment.find(comment.id).user
		= link_to "Editar", edit_post_comment_path(comment.post, comment), :class => 'btn amber accent-3'
		= link_to "Excluir", [comment.post, comment], method: :delete, data: { confirm: "Deseja realmente apagar esse comentário?" }, :class => 'btn red'

forum/app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :comment
	= f.submit "Criar comentário", :class => 'btn light-green accent-4'

forum/app/views/comments/edit.html.haml
%h1.container
	.card-panel.valign
		.center-align
			Editar Comentário
.container
	= simple_form_for([@post, @comment]) do |f|
		= f.input :comment
		= f.submit "Atualizar", :class => 'btn light-green accent-4'
		= link_to "Cancelar", :back, :class => 'btn red'

forum/app/views/layouts/application.html.haml
!!!
%html
%head
	%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
	%meta{:content => "width=device-width, initial-scale=1, maximum-scale=1.0", :name => "viewport"}
	%title MJ-Share
	= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
	%link{:rel => "stylesheet", :href => "https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css"}
	%link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}
	%link{:href => "css/materialize.css", :media => "screen,projection", :rel => "stylesheet", :type => "text/css"}/
	%link{:href => "css/style.css", :media => "screen,projection", :rel => "stylesheet", :type => "text/css"}/
	= javascript_include_tag 'application', 'data-turbolinks-track' => true 
	= csrf_meta_tags
%body
	%nav.light-blue.lighten-1{:role => "navigation"}
		.nav-wrapper.container
			.row.clearfix
				%a#logo-container.brand-logo{:href => root_path } MJ-Share Fórum
				- if user_signed_in?
					.col.offset-s7
						%strong Bem vindo(a)
						%strong 
							=current_user.username
						%strong !

					=link_to "Usuário", edit_user_registration_path, class: 'col'
					=link_to "Novo Post", new_post_path, class: 'col'
					=link_to "Contato", contact_path, class: 'col'
					=link_to "Sobre", about_path, class: 'col'
					=link_to "Sair", destroy_user_session_path, :method => :delete, data: {confirm: "Deseja realmente sair?"}, class: 'col'
				- else
					.col.offset-s7
						%strong Bem vindo(a) visitante!
					=link_to "Entrar", new_user_session_path, class: 'col'
					=link_to "Inscreva-se", new_user_registration_path, class: 'col'
					=link_to "Contato", contact_path, class: 'col'
					=link_to "Sobre", about_path, class: 'col'

	.wrapper
		%p.notice= notice
		%p.alert= alert

	.wrapper
		= yield

forum/app/views/posts/_form.html.haml
.container
	= simple_form_for @post do |f|
		= f.input :title 
		= f.input :content
		= f.submit "Criar Post", :class => 	'btn light-green accent-4'
		= link_to "Cancelar", :back, :class => 'btn red'

forum/app/views/posts/about.html.haml
%h2.container
	.card-panel.valign
		Hey Listen...
		%img{:alt => "", :height => "50", :src => "https://upload.wikimedia.org/wikipedia/en/0/04/Navi_(The_Legend_of_Zelda).png", :width => "50"}/

%p.container
	Nós do
	%strong MJ-Share
	somos uma comunidade, o intuito do nosso fórum é compartilhar a internet entre amigos, tudo que você procura certamente temos aqui!
%h1.container 
	.card-panel.valign
		Regras do Fórum
%p.container 1 - Seja cordial com todos os usuários do Fórum.
%p.container 2 - São proibidos arquivos com referência/conteúdo pornográfico, racista, hacker, que contenha vírus ou outros semelhantes, (seja por motivos de religião, sexo, raça, convicção politica, esportiva ou outro tipo assim considerado, que possa causar conflito), incluindo comentários.
%p.container 3 - Não são permitidos arquivos demo, jogos online com acesso por cadastro, versão alphas e betas de jogos e software, keygens, crackers e traduções lançados separadamente dos seus respectivos programas. Aplicativos/softwares sem desenvolvedor oficial serão excluídos.
%p.container 4 - A qualquer momento o seu post pode ser deletado ou editado caso um moderador/admin julgar necessário.
%p.container 5 - Proibido publicidade comercial, fazer spam, spoiler e linguagens impróprias.
%p.container 6 - O não cumprimento das regras supracitadas podem levar a expulsão do membro.
%p.container O conhecimento dessas regras e sua leitura são da responsabilidade de cada membro. Registrando-se nesse fórum, você declara compreender e aceitar as regras que regem este presente fórum, e estas regras tem o único propósito de garantir o bem-estar e a convivência pacífica entre os membros do fórum.

forum/app/views/posts/contact.html.haml
%h2.container
	.card-panel.valign
		Contatos

%p.container
	Para mais informações, ou dúvidas, entre em contato com os desenvolvedores pelos emails:
.row
	%h4.container.col.s4.offset-s2
		.card-panel.valing
			%strong Mariana Mendes:
			%br/
			mare.s.mendes@gmail.com

	%h4.container.col.s4
		.card-panel.valign
			%strong João Pedro Sconetto:
			%br/
			sconetto.joao@gmail.com

forum/app/views/posts/edit.html.haml
%h1.container
	.card-panel.valign
		.center-align
			Editar Post

.container
	= simple_form_for @post do |f|
		= f.input :title
		= f.input :content
		= f.submit "Editar Post", :class => 'btn light-green accent-4'
		= link_to "Cancelar", :back, :class => 'btn red'

forum/app/views/posts/index.html.haml
.container
	- @posts.each do |post|
		.card-panel.valign.z-depth-1
			%h2.title= link_to post.title, post
			%p.date
				Publicado
				= time_ago_in_words(post.created_at)
				atrás por 
				= post.user.username
				| email:
				= post.user.email

forum/app/views/posts/new.html.haml
%h1.container
	.card-panel.valign
		.center-align
			Novo Post 

= render 'form'

forum/app/views/posts/show.html.haml
.container
	%h2.grey-text.text-darken-2
		%strong
			= @post.title
	%h5= @post.content
	
	%hr/

	%h5
		.right-align
			= @post.comments.count
			Comentário(s)
	
	= render @post.comments

	%hr/

	%h4 Responder
	= render "comments/form"
	
	%br/
	%hr/
	%br/
	= link_to "Início", root_path, :class => 'btn light-blue lighten-1'		
	- if current_user == Post.find(@post).user
		= link_to "Editar", edit_post_path(@post), :class => 'btn amber accent-3'
		= link_to "Apagar Post", post_path(@post), method: :delete, data: {confirm: "Deseja realmente apagar este post?"}, :class => 'btn red'